"use client";

import Link from "next/link";
import { useEffect, useState, type FormEvent } from "react";
import { ArrowLeft, LocateFixed, Radio, Trash2 } from "lucide-react";
import type { CameraRecord } from "@/lib/camera";

const STORAGE_KEY = "public-cam-atlas-dashcams";

function readConnected(): CameraRecord[] {
  try { return JSON.parse(localStorage.getItem(STORAGE_KEY) || "[]"); } catch { return []; }
}

function streamKind(raw: string) {
  const url = new URL(raw);
  if (url.protocol !== "https:" || url.username || url.password) throw new Error("Use a public HTTPS source without credentials in the URL.");
  if (url.hostname === "youtu.be") return "youtube" as const;
  if (url.hostname.endsWith("youtube.com") && url.searchParams.get("v")) return "youtube" as const;
  if (url.pathname.toLowerCase().endsWith(".m3u8")) return "hls" as const;
  throw new Error("Use a direct HTTPS .m3u8 feed or a YouTube Live watch URL.");
}

export default function ConnectDashcam() {
  const [connected, setConnected] = useState<CameraRecord[]>([]);
  const [message, setMessage] = useState("");
  useEffect(() => {
    const timer = window.setTimeout(() => setConnected(readConnected()), 0);
    return () => window.clearTimeout(timer);
  }, []);

  const locate = () => navigator.geolocation?.getCurrentPosition(({ coords }) => {
    const lat = document.querySelector<HTMLInputElement>('input[name="lat"]');
    const lng = document.querySelector<HTMLInputElement>('input[name="lng"]');
    if (lat) lat.value = coords.latitude.toFixed(6);
    if (lng) lng.value = coords.longitude.toFixed(6);
  }, () => setMessage("Location permission was not available. Enter the coordinates manually."));

  const submit = (event: FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    const form = new FormData(event.currentTarget);
    try {
      let streamUrl = String(form.get("streamUrl") || "").trim();
      const streamType = streamKind(streamUrl);
      const parsed = new URL(streamUrl);
      if (parsed.hostname === "youtu.be") streamUrl = `https://www.youtube.com/watch?v=${parsed.pathname.slice(1)}`;
      const lat = Number(form.get("lat"));
      const lng = Number(form.get("lng"));
      if (!Number.isFinite(lat) || lat < -90 || lat > 90 || !Number.isFinite(lng) || lng < -180 || lng > 180) throw new Error("Enter valid latitude and longitude.");
      if (form.get("authorized") !== "yes") throw new Error("The camera owner must authorize public broadcasting.");
      const title = String(form.get("title") || "Live dashcam").trim();
      const region = String(form.get("region") || "Mobile").trim();
      const state = String(form.get("state") || "United States").trim();
      const camera: CameraRecord = {
        id: `dashcam-${crypto.randomUUID()}`,
        title, sourceUrl: streamUrl, streamUrl, streamType, lat, lng,
        operator: String(form.get("operator") || "Participating dashcam owner").trim(),
        sourcePage: streamUrl, status: "unknown", lastChecked: null, region, state,
        category: "dashcam", publicationEvidence: "Camera owner attested that this live feed is intentionally public",
        discoveryMethod: "Direct owner/fleet connection", accessClassification: "verified_public",
        authentication: "none", inclusionRationale: "Live source supplied directly by the camera owner; no uploaded or reposted video",
      };
      const next = [...readConnected(), camera];
      localStorage.setItem(STORAGE_KEY, JSON.stringify(next));
      setConnected(next);
      setMessage("Connected. This direct live source is now available in your Atlas under Type → Live dashcam.");
      event.currentTarget.reset();
    } catch (error) { setMessage(error instanceof Error ? error.message : "Could not connect this feed."); }
  };

  const remove = (id: string) => {
    const next = readConnected().filter((camera) => camera.id !== id);
    localStorage.setItem(STORAGE_KEY, JSON.stringify(next));
    setConnected(next);
  };

  return <main className="connect-page">
    <Link href="/" className="back-link"><ArrowLeft size={16}/> Back to map</Link>
    <section className="connect-hero"><span className="eyebrow">Direct source connection</span><h1>Connect a live dashcam.</h1><p>Use the camera owner’s live output—not an uploaded clip. The feed stays at its source and plays in the Atlas.</p></section>
    <div className="connect-layout">
      <form className="connect-form" onSubmit={submit}>
        <div className="form-intro"><Radio size={18}/><div><strong>Owner or fleet feed</strong><span>HTTPS HLS (.m3u8) or a YouTube Live broadcast generated by the camera owner.</span></div></div>
        <label>Camera name<input name="title" required placeholder="Downtown route dashcam"/></label>
        <label>Live source URL<input name="streamUrl" type="url" required placeholder="https://stream.example.com/live/camera.m3u8"/></label>
        <div className="form-two"><label>Operator<input name="operator" required placeholder="Owner or fleet name"/></label><label>City / area<input name="region" required placeholder="San Antonio"/></label></div>
        <div className="form-three"><label>State<input name="state" required placeholder="Texas"/></label><label>Latitude<input name="lat" required inputMode="decimal" placeholder="29.4241"/></label><label>Longitude<input name="lng" required inputMode="decimal" placeholder="-98.4936"/></label></div>
        <button className="locate-button" type="button" onClick={locate}><LocateFixed size={15}/> Use this device’s location</button>
        <label className="consent"><input name="authorized" value="yes" type="checkbox" required/><span>I own or operate this camera, or I’m authorized to publish its live feed publicly.</span></label>
        <button className="connect-submit" type="submit">Connect live source</button>
        {message && <p className="form-message" role="status">{message}</p>}
      </form>
      <aside className="connected-list"><h2>Connected on this device</h2><p>These feeds appear immediately on your map and video wall.</p>{connected.length === 0 ? <div className="empty-connected">No direct dashcams connected yet.</div> : connected.map((camera) => <div className="connected-item" key={camera.id}><span><strong>{camera.title}</strong><small>{camera.region} · {camera.streamType}</small></span><button onClick={() => remove(camera.id)} aria-label={`Remove ${camera.title}`}><Trash2 size={15}/></button></div>)}</aside>
    </div>
  </main>;
}
